// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ojp.proto

package com.bliksemlabs.ojp;

public final class OJP {
  private OJP() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_ojp_OJPLocationInformationRequest_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ojp_OJPLocationInformationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_ojp_OJPLocationInformationDelivery_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ojp_OJPLocationInformationDelivery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_ojp_OJPExchangePointsRequest_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ojp_OJPExchangePointsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_ojp_OJPExchangePointsDelivery_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ojp_OJPExchangePointsDelivery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_ojp_OJPTripRequest_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ojp_OJPTripRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_ojp_OJPTripDelivery_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ojp_OJPTripDelivery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_ojp_OJPMultiPointTripRequest_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ojp_OJPMultiPointTripRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_ojp_OJPMultiPointTripDelivery_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ojp_OJPMultiPointTripDelivery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_ojp_OJPStopEventRequest_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ojp_OJPStopEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_ojp_OJPStopEventDelivery_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ojp_OJPStopEventDelivery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_ojp_OJPTripInfoRequest_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ojp_OJPTripInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_ojp_OJPTripInfoDelivery_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ojp_OJPTripInfoDelivery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_ojp_OJPFareRequest_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ojp_OJPFareRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_ojp_OJPFareDelivery_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ojp_OJPFareDelivery_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
        "\n\tojp.proto\022\003ojp\032\0228_03_generic.proto\032\0348_" +
            "04_10_requestsupport.proto\032\0248_05_locatio" +
            "ns.proto\032\0208_07_trips.proto\032\0258_08_stopeve" +
            "nts.proto\032\0238_09_tripinfo.proto\032\0178_10_far" +
            "e.proto\"\312\001\n\035OJPLocationInformationReques" +
            "t\022\'\n\016serviceRequest\030\001 \001(\0132\017.ServiceReque" +
            "st\022=\n\031abstractOJPServiceRequest\030\002 \001(\0132\032." +
            "AbstractOJPServiceRequest\022A\n\034locatationI" +
            "nformationRequest\030\003 \001(\0132\033.LocationInform" +
            "ationRequest\"\275\002\n\036OJPLocationInformationD" +
            "elivery\022)\n\017serviceDelivery\030\001 \001(\0132\020.Servi" +
            "ceDelivery\0229\n\027abstractServiceDelivery\030\002 " +
            "\001(\0132\030.AbstractServiceDelivery\022?\n\032locatio" +
            "nInformationRequest\030\003 \001(\0132\033.LocationInfo" +
            "rmationRequest\0227\n\026serviceResponseContext" +
            "\030\004 \001(\0132\027.ServiceResponseContext\022;\n\030place" +
            "InformationResponse\030\005 \001(\0132\031.PlaceInforma" +
            "tionResponse\"\271\001\n\030OJPExchangePointsReques" +
            "t\022\'\n\016serviceRequest\030\001 \001(\0132\017.ServiceReque" +
            "st\022=\n\031abstractOJPServiceRequest\030\002 \001(\0132\032." +
            "AbstractOJPServiceRequest\0225\n\025exchangePoi" +
            "ntsRequest\030\003 \001(\0132\026.ExchangePointsRequest" +
            "\"\252\002\n\031OJPExchangePointsDelivery\022)\n\017servic" +
            "eDelivery\030\001 \001(\0132\020.ServiceDelivery\0229\n\027abs" +
            "tractServiceDelivery\030\002 \001(\0132\030.AbstractSer" +
            "viceDelivery\0225\n\025exchangePointsRequest\030\003 " +
            "\001(\0132\026.ExchangePointsRequest\0227\n\026serviceRe" +
            "sponseContext\030\004 \001(\0132\027.ServiceResponseCon" +
            "text\0227\n\026exchangePointsResponse\030\005 \001(\0132\027.E" +
            "xchangePointsResponse\"\233\001\n\016OJPTripRequest" +
            "\022\'\n\016serviceRequest\030\001 \001(\0132\017.ServiceReques" +
            "t\022=\n\031abstractOJPServiceRequest\030\002 \001(\0132\032.A" +
            "bstractOJPServiceRequest\022!\n\013tripRequest\030" +
            "\003 \001(\0132\014.TripRequest\"\370\001\n\017OJPTripDelivery\022" +
            ")\n\017serviceDelivery\030\001 \001(\0132\020.ServiceDelive" +
            "ry\0229\n\027abstractServiceDelivery\030\002 \001(\0132\030.Ab" +
            "stractServiceDelivery\022!\n\013tripRequest\030\003 \001" +
            "(\0132\014.TripRequest\0227\n\026serviceResponseConte" +
            "xt\030\004 \001(\0132\027.ServiceResponseContext\022#\n\014tri" +
            "pResponse\030\005 \001(\0132\r.TripResponse\"\271\001\n\030OJPMu" +
            "ltiPointTripRequest\022\'\n\016serviceRequest\030\001 " +
            "\001(\0132\017.ServiceRequest\022=\n\031abstractOJPServi" +
            "ceRequest\030\002 \001(\0132\032.AbstractOJPServiceRequ" +
            "est\0225\n\025multiPointTripRequest\030\003 \001(\0132\026.Mul" +
            "tiPointTripRequest\"\252\002\n\031OJPMultiPointTrip" +
            "Delivery\022)\n\017serviceDelivery\030\001 \001(\0132\020.Serv" +
            "iceDelivery\0229\n\027abstractServiceDelivery\030\002" +
            " \001(\0132\030.AbstractServiceDelivery\0225\n\025multiP" +
            "ointTripRequest\030\003 \001(\0132\026.MultiPointTripRe" +
            "quest\0227\n\026serviceResponseContext\030\004 \001(\0132\027." +
            "ServiceResponseContext\0227\n\026multiPointTrip" +
            "Response\030\005 \001(\0132\027.MultiPointTripResponse\"" +
            "\252\001\n\023OJPStopEventRequest\022\'\n\016serviceReques" +
            "t\030\001 \001(\0132\017.ServiceRequest\022=\n\031abstractOJPS" +
            "erviceRequest\030\002 \001(\0132\032.AbstractOJPService" +
            "Request\022+\n\020stopEventRequest\030\003 \001(\0132\021.Stop" +
            "EventRequest\"\221\002\n\024OJPStopEventDelivery\022)\n" +
            "\017serviceDelivery\030\001 \001(\0132\020.ServiceDelivery" +
            "\0229\n\027abstractServiceDelivery\030\002 \001(\0132\030.Abst" +
            "ractServiceDelivery\022+\n\020stopEventRequest\030" +
            "\003 \001(\0132\021.StopEventRequest\0227\n\026serviceRespo" +
            "nseContext\030\004 \001(\0132\027.ServiceResponseContex" +
            "t\022-\n\021stopEventResponse\030\005 \001(\0132\022.StopEvent" +
            "Response\"\247\001\n\022OJPTripInfoRequest\022\'\n\016servi" +
            "ceRequest\030\001 \001(\0132\017.ServiceRequest\022=\n\031abst" +
            "ractOJPServiceRequest\030\002 \001(\0132\032.AbstractOJ" +
            "PServiceRequest\022)\n\017tripInfoRequest\030\003 \001(\013" +
            "2\020.TripInfoRequest\"\214\002\n\023OJPTripInfoDelive" +
            "ry\022)\n\017serviceDelivery\030\001 \001(\0132\020.ServiceDel" +
            "ivery\0229\n\027abstractServiceDelivery\030\002 \001(\0132\030" +
            ".AbstractServiceDelivery\022)\n\017tripInfoRequ" +
            "est\030\003 \001(\0132\020.TripInfoRequest\0227\n\026serviceRe" +
            "sponseContext\030\004 \001(\0132\027.ServiceResponseCon" +
            "text\022+\n\020tripInfoResponse\030\005 \001(\0132\021.TripInf" +
            "oResponse\"\233\001\n\016OJPFareRequest\022\'\n\016serviceR" +
            "equest\030\001 \001(\0132\017.ServiceRequest\022=\n\031abstrac" +
            "tOJPServiceRequest\030\002 \001(\0132\032.AbstractOJPSe" +
            "rviceRequest\022!\n\013fareRequest\030\003 \001(\0132\014.Fare" +
            "Request\"\370\001\n\017OJPFareDelivery\022)\n\017serviceDe" +
            "livery\030\001 \001(\0132\020.ServiceDelivery\0229\n\027abstra" +
            "ctServiceDelivery\030\002 \001(\0132\030.AbstractServic" +
            "eDelivery\022!\n\013fareRequest\030\003 \001(\0132\014.FareReq" +
            "uest\0227\n\026serviceResponseContext\030\004 \001(\0132\027.S" +
            "erviceResponseContext\022#\n\014fareResponse\030\005 " +
            "\001(\0132\r.FareResponse2\330\004\n\022OpenJourneyPlanne" +
            "r\022k\n getOJPLocationInformationRequest\022\"." +
            "ojp.OJPLocationInformationRequest\032#.ojp." +
            "OJPLocationInformationDelivery\022\\\n\033getOJP" +
            "ExchangePointsRequest\022\035.ojp.OJPExchangeP" +
            "ointsRequest\032\036.ojp.OJPExchangePointsDeli" +
            "very\022>\n\021getOJPTripRequest\022\023.ojp.OJPTripR" +
            "equest\032\024.ojp.OJPTripDelivery\022\\\n\033getOJPMu" +
            "ltiPointTripRequest\022\035.ojp.OJPMultiPointT" +
            "ripRequest\032\036.ojp.OJPMultiPointTripDelive" +
            "ry\022M\n\026getOJPStopEventRequest\022\030.ojp.OJPSt" +
            "opEventRequest\032\031.ojp.OJPStopEventDeliver" +
            "y\022J\n\025getOJPTripInfoRequest\022\027.ojp.OJPTrip" +
            "InfoRequest\032\030.ojp.OJPTripInfoDelivery\022>\n" +
            "\021getOJPFareRequest\022\023.ojp.OJPFareRequest\032" +
            "\024.ojp.OJPFareDeliveryB\"\n\023com.bliksemlabs" +
            ".ojpB\003OJPP\001\242\002\003OJPb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
                803Generic.getDescriptor(),
                80410Requestsupport.getDescriptor(),
                805Locations.getDescriptor(),
                807Trips.getDescriptor(),
                808Stopevents.getDescriptor(),
                809Tripinfo.getDescriptor(),
                810Fare.getDescriptor(),
            }, assigner);
    internal_static_ojp_OJPLocationInformationRequest_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_ojp_OJPLocationInformationRequest_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ojp_OJPLocationInformationRequest_descriptor,
        new java.lang.String[] { "ServiceRequest", "AbstractOJPServiceRequest", "LocatationInformationRequest", });
    internal_static_ojp_OJPLocationInformationDelivery_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_ojp_OJPLocationInformationDelivery_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ojp_OJPLocationInformationDelivery_descriptor,
        new java.lang.String[] { "ServiceDelivery", "AbstractServiceDelivery", "LocationInformationRequest", "ServiceResponseContext", "PlaceInformationResponse", });
    internal_static_ojp_OJPExchangePointsRequest_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_ojp_OJPExchangePointsRequest_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ojp_OJPExchangePointsRequest_descriptor,
        new java.lang.String[] { "ServiceRequest", "AbstractOJPServiceRequest", "ExchangePointsRequest", });
    internal_static_ojp_OJPExchangePointsDelivery_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_ojp_OJPExchangePointsDelivery_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ojp_OJPExchangePointsDelivery_descriptor,
        new java.lang.String[] { "ServiceDelivery", "AbstractServiceDelivery", "ExchangePointsRequest", "ServiceResponseContext", "ExchangePointsResponse", });
    internal_static_ojp_OJPTripRequest_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_ojp_OJPTripRequest_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ojp_OJPTripRequest_descriptor,
        new java.lang.String[] { "ServiceRequest", "AbstractOJPServiceRequest", "TripRequest", });
    internal_static_ojp_OJPTripDelivery_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_ojp_OJPTripDelivery_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ojp_OJPTripDelivery_descriptor,
        new java.lang.String[] { "ServiceDelivery", "AbstractServiceDelivery", "TripRequest", "ServiceResponseContext", "TripResponse", });
    internal_static_ojp_OJPMultiPointTripRequest_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_ojp_OJPMultiPointTripRequest_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ojp_OJPMultiPointTripRequest_descriptor,
        new java.lang.String[] { "ServiceRequest", "AbstractOJPServiceRequest", "MultiPointTripRequest", });
    internal_static_ojp_OJPMultiPointTripDelivery_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_ojp_OJPMultiPointTripDelivery_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ojp_OJPMultiPointTripDelivery_descriptor,
        new java.lang.String[] { "ServiceDelivery", "AbstractServiceDelivery", "MultiPointTripRequest", "ServiceResponseContext", "MultiPointTripResponse", });
    internal_static_ojp_OJPStopEventRequest_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_ojp_OJPStopEventRequest_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ojp_OJPStopEventRequest_descriptor,
        new java.lang.String[] { "ServiceRequest", "AbstractOJPServiceRequest", "StopEventRequest", });
    internal_static_ojp_OJPStopEventDelivery_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_ojp_OJPStopEventDelivery_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ojp_OJPStopEventDelivery_descriptor,
        new java.lang.String[] { "ServiceDelivery", "AbstractServiceDelivery", "StopEventRequest", "ServiceResponseContext", "StopEventResponse", });
    internal_static_ojp_OJPTripInfoRequest_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_ojp_OJPTripInfoRequest_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ojp_OJPTripInfoRequest_descriptor,
        new java.lang.String[] { "ServiceRequest", "AbstractOJPServiceRequest", "TripInfoRequest", });
    internal_static_ojp_OJPTripInfoDelivery_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_ojp_OJPTripInfoDelivery_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ojp_OJPTripInfoDelivery_descriptor,
        new java.lang.String[] { "ServiceDelivery", "AbstractServiceDelivery", "TripInfoRequest", "ServiceResponseContext", "TripInfoResponse", });
    internal_static_ojp_OJPFareRequest_descriptor =
        getDescriptor().getMessageTypes().get(12);
    internal_static_ojp_OJPFareRequest_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ojp_OJPFareRequest_descriptor,
        new java.lang.String[] { "ServiceRequest", "AbstractOJPServiceRequest", "FareRequest", });
    internal_static_ojp_OJPFareDelivery_descriptor =
        getDescriptor().getMessageTypes().get(13);
    internal_static_ojp_OJPFareDelivery_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ojp_OJPFareDelivery_descriptor,
        new java.lang.String[] { "ServiceDelivery", "AbstractServiceDelivery", "FareRequest", "ServiceResponseContext", "FareResponse", });
    803Generic.getDescriptor();
    80410Requestsupport.getDescriptor();
    805Locations.getDescriptor();
    807Trips.getDescriptor();
    808Stopevents.getDescriptor();
    809Tripinfo.getDescriptor();
    810Fare.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}